# Generated by Django 2.1.7 on 2019-04-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(upload_to='about')),
                ('description', models.TextField()),
                ('question', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('ex_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(upload_to='blog')),
                ('description', models.TextField()),
                ('ex_title', models.CharField(blank=True, max_length=250, null=True)),
                ('ex_description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('client_logo', models.ImageField(upload_to='client')),
            ],
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=250)),
                ('edu_description', models.TextField()),
                ('edu_cartificate', models.ImageField(blank=True, upload_to='edu')),
                ('edu_start_time', models.DateField()),
                ('edu_end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_exp_name', models.CharField(max_length=250)),
                ('job_holder_title', models.CharField(max_length=250)),
                ('job_description', models.TextField()),
                ('job_start_time', models.DateField()),
                ('job_end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FontModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(upload_to='fontViews')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=250)),
                ('contact_number', models.CharField(max_length=250)),
                ('dreame', models.TextField()),
                ('focusing', models.TextField()),
                ('copy_right', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(upload_to='projects')),
                ('description', models.TextField()),
                ('ex_title', models.CharField(max_length=250)),
                ('ex_description', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('developer_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_person_name', models.CharField(max_length=250)),
                ('recommend_person_company_name', models.CharField(max_length=250)),
                ('recommend_person_position', models.CharField(max_length=250)),
                ('recommend_person_anounce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(upload_to='skills')),
            ],
        ),
        migrations.CreateModel(
            name='SocialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=250)),
                ('social_image', models.ImageField(upload_to='social')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=250)),
                ('dev_title', models.CharField(max_length=250)),
                ('dev_img', models.ImageField(upload_to='teammember')),
                ('member_description', models.TextField()),
                ('dev_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protfolio.SocialModel')),
            ],
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protfolio.TagModel'),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protfolio.TagModel'),
        ),
    ]
